### ISSUE TITLE
Typo in npm package

### ISSUE THREAD

**Issue by mauriciabad** [petoc/Leaflet.DoubleTouchDragZoom#2]
Hi, you published the package with a typo (missing second L of leafLet).

You can unpublish the package only within a certain time window, so this is quite **URGENT**...

No worries, this things happen.

`@petoc/leafet-double-touch-drag-zoom` should become `@petoc/leaflet-double-touch-drag-zoom`

Related to #1

**Comment by petoc** [comment]
Hi, totally missed that. Package should be now available with correct name.
And thank you for alerting me.
