### ISSUE TITLE
Broken normal zoom gesture.

### ISSUE THREAD

**Issue by mauriciabad** [petoc/Leaflet.DoubleTouchDragZoom#3]
https://github.com/petoc/Leaflet.DoubleTouchDragZoom/assets/12821361/6ea9390d-7b25-4631-807b-dab1a1dfefeb

Zooming with two fingers regularly triggers the one finger gesture, leading to the opposite zoom intended.

**Comment by petoc** [comment]
Thanks again, should be working now. Please let me know, if it is working for you.

**Comment by mauriciabad** [comment]
It works perfectly 😄 🎉
